@Library('shared') _


pipeline {
    agent { label 'slave' }
    
    environment {
        GIT_EMAIL = 'm.ebadarshad2003@gmail.com'
        APP_NAME = 'order'
        IMAGE_NAME = "ebadarshad/ecommerce-${APP_NAME}"
        REPO_URL = "github.com/ebad-arshad/aws-devops-gitops-platform.git"
        BASE_VERSION = "1.0" 
        VERSION = "${env.BASE_VERSION}.${env.BUILD_NUMBER}"
    }
    
    stages{
        
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Sparse Checkout') {
            steps {
                // We use the full 'checkout' step instead of just 'git'
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [
                        [$class: 'CleanBeforeCheckout'],
                        [$class: 'SparseCheckoutPaths', 
                        sparseCheckoutPaths: [
                            [$class: 'SparseCheckoutPath', path: "app/${env.APP_NAME}/"], 
                            [$class: 'SparseCheckoutPath', path: 'k8s/'],
                        ]]
                    ],  
                    userRemoteConfigs: [[url: "https://${env.REPO_URL}"]]
                ])
            }
        }

        stage('Check Changes') {
            steps {
                dir("app/${env.APP_NAME}") {
                    script {
                    def lastCommitMsg = sh(
                        script: "git log -1 --pretty=%B",
                        returnStdout: true
                    ).trim()

                    if (lastCommitMsg.startsWith("CI:")) {
                        echo "GitOps commit detected. Skipping pipeline."
                        env.SHOULD_BUILD = 'false'
                        return
                    }

                    def status = sh(
                        script: """
                            git diff --name-only HEAD~1 HEAD | grep -E '^app/${env.APP_NAME}/'
                        """,
                        returnStatus: true
                    )

                    if (status == 0) {
                        env.SHOULD_BUILD = 'true'
                        echo "App changes detected for ${env.APP_NAME}"
                    } else {
                        env.SHOULD_BUILD = 'false'
                        echo "No app changes detected for ${env.APP_NAME}"
                    }
                }
                }
            }
        }

        // stage('Security Scan (Code)') {
            //             when { expression { return env.SHOULD_BUILD == "true" } }
        //     steps {
        //         // SAST: Find secrets/vulns in your source code
        //         sh "trivy fs app/${env.APP_NAME} --severity HIGH,CRITICAL --exit-code 1"
        //     }
        // }

        stage('Login DockerHub') {
            when { expression { return env.SHOULD_BUILD == "true" } }
            steps {
                script {
                    dockerhub_login('docker-hub-creds')
                }
            }
        }

        stage('Build, Scan & Push') {
            when { expression { return env.SHOULD_BUILD == "true" } } 

            steps {
                sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} app/${env.APP_NAME}/"
                // sh "trivy image ${env.IMAGE_NAME}:${env.VERSION} --severity HIGH,CRITICAL"
                sh "docker push ${env.IMAGE_NAME}:${env.VERSION}" 
            }
        }

        stage('GitOps Update') {
            when { expression { return env.SHOULD_BUILD == "true" } }

            steps {
                dir('k8s/overlays/dev/base') {
                    withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                        sh """
                            sed -i 's|${IMAGE_NAME}:[^ ]*|${IMAGE_NAME}:${env.VERSION}|g' ${env.APP_NAME}-patch.yaml
                            
                            git add ${env.APP_NAME}-patch.yaml

                            if ! git diff --cached --quiet; then
                                git commit -m 'CI: Updated Image ${env.IMAGE_NAME} env.version to ${env.VERSION} , Author: ${env.GIT_EMAIL}'
                                git push https://${env.GIT_TOKEN}@${env.REPO_URL} HEAD:master
                            else
                                echo "No changes to commit"
                            fi
                        """
                    }   
                }
            }
        }
    }
}