apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana-project
  namespace: argocd # Projects must be created in the Argo CD namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  description: This ecommerce project will be for grafana
  sourceRepos:
  - 'https://github.com/ebad-arshad/aws-devops-gitops-platform'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://open-telemetry.github.io/opentelemetry-helm-charts'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'