@Library('shared') _


pipeline {
    agent { label 'slave' }

    stages{
        stage('Semantic Versioning') {
            steps{
                script {
                    def BASE_VERSION = "1.0"
                    env.VERSION = "${BASE_VERSION}.${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Sparse Checkout') {
            steps {
                // We use the full 'checkout' step instead of just 'git'
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [
                        [$class: 'SparseCheckoutPaths', 
                        sparseCheckoutPaths: [
                            [$class: 'SparseCheckoutPath', path: "app/"], // e.g., auth/
                            [$class: 'SparseCheckoutPath', path: 'k8s/'],         // Your manifests
                            [$class: 'SparseCheckoutPath', path: 'jenkins/']      // The Jenkinsfile itself
                        ]]
                    ], 
                    userRemoteConfigs: [[url: 'https://github.com/ebad-arshad/aws-devops-gitops-platform.git']]
                ])
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'ls -ltr'
                }
            }
        }

    }
}