@Library('shared') _


pipeline {
    agent { label 'slave' }
    
    environment {
        GIT_EMAIL = 'm.ebadarshad2003@gmail.com'
        APP_NAME = 'product'
        IMAGE_NAME = "ebadarshad/ecommerce-${APP_NAME}"
        REPO_URL = "github.com/ebad-arshad/aws-devops-gitops-platform.git"
        BASE_VERSION = "1.0" 
        VERSION = "${env.BASE_VERSION}.${env.BUILD_NUMBER}"
    }
    
    stages{

        stage('Check Changes') {
            steps {
                script {
                    def status = sh(script: """
                        if git rev-parse HEAD~1 >/dev/null 2>&1; then
                            git diff --name-only HEAD~1 HEAD | grep -E '^(app/${env.APP_NAME}/)'
                        else
                            exit 0
                        fi
                    """, returnStatus: true)

                    if (status == 0) {
                        env.SHOULD_BUILD = 'true'
                        echo env.SHOULD_BUILD
                        echo "MATCH FOUND! Proceeding with build for ${env.APP_NAME}"
                    } else {
                        echo "NO MATCH. Skipping build for ${env.APP_NAME}"
                    }
                }
            }
        }


        stage('Sparse Checkout') {
            when { expression { return env.SHOULD_BUILD == "true" } }
            steps {
                // We use the full 'checkout' step instead of just 'git'
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/master']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [
                        [$class: 'CleanBeforeCheckout'],
                        [$class: 'PollingIgnoreCommitMessages', excludedMessage: '.*\\[skip ci\\].*'],
                        [$class: 'SparseCheckoutPaths', 
                        sparseCheckoutPaths: [
                            [$class: 'SparseCheckoutPath', path: "app/${env.APP_NAME}/"], 
                            [$class: 'SparseCheckoutPath', path: 'k8s/'],
                        ]]
                    ],  
                    userRemoteConfigs: [[url: "https://${env.REPO_URL}"]]
                ])
            }
        }

        // stage('Security Scan (Code)') {
            //             when { expression { return env.SHOULD_BUILD == "true" } }
        //     steps {
        //         // SAST: Find secrets/vulns in your source code
        //         sh "trivy fs app/${env.APP_NAME} --severity HIGH,CRITICAL --exit-code 1"
        //     }
        // }

        stage('Login DockerHub') {
            when { expression { return env.SHOULD_BUILD == "true" } }
            steps {
                script {
                    dockerhub_login('docker-hub-creds')
                }
            }
        }

        stage('Build, Scan & Push') {
            when { expression { return env.SHOULD_BUILD == "true" } }

            steps {
                sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} app/${env.APP_NAME}/"
                // sh "trivy image ${env.IMAGE_NAME}:${env.VERSION} --severity HIGH,CRITICAL"
                sh "docker push ${env.IMAGE_NAME}:${env.VERSION}"
            }
        }

        stage('GitOps Update') {
            when { expression { return env.SHOULD_BUILD == "true" } }

            steps {
                dir('k8s/overlays/dev') {
                    // Update ONLY the image for this specific microservice
                    sh "kustomize edit set image ${env.IMAGE_NAME}=${env.IMAGE_NAME}:${env.VERSION}"
                }
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                        sh """
                            git add k8s/overlays/dev/kustomization.yaml

                            if ! git diff --cached --quiet; then
                                git commit -m 'Author: ${env.GIT_EMAIL} , CI: Updated Image ${env.IMAGE_NAME} env.version to ${env.VERSION} [skip ci]'
                                
                                git push https://${env.GIT_TOKEN}@${env.REPO_URL} HEAD:master
                            fi
                        """
                    }
                }
            }
        }

    }
}